[env:4d_systems_esp32s3_gen4_r8n16]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
monitor_speed = 115200

lib_deps =
    # Use the official ESP32 version of AsyncTCP
    https://github.com/me-no-dev/AsyncTCP.git
    # Use the official WebServer
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    # Your other existing libraries
    madhephaestus/ESP32Servo
    adafruit/Adafruit NeoPixel
